spring.application.name=conference-service
server.port=8081

# Database configuration
spring.datasource.url=jdbc:postgresql://ep-cool-bread-anansxll.c-6.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_iT9ENjMpwv1B&sslmode=require&channelBinding=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger/OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.try-it-out-enabled=true

# Desactiva seguridad automática para prueba rápida
spring.security.user.name=sa
spring.security.user.password=sa
spring.security.user.roles=USER
spring.security.enabled=false